mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from web3auth import urls as web3auth_urls
urlpatterns = [
	url(r'etherfeeds/', include('etherfeeds.urls')),
	url(r'pollSite/', include('pollSite.urls')),
	url(r'pageEval/', include('pageEval.urls')),
	url(r'web3auth/',include(web3auth_urls)),
    url(r'admin/', admin.site.urls),
]

pollSite/urls.py
#pollSite

from django.conf.urls import url
from . import views

app_name = 'pollSite'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<siteId>[0-9]+)/(?P<PersonId>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'newPerson',views.newPerson,name='newPerson'),
	url(r'register', views.register, name='register'),
    url(r'thanks', views.thanks, name='thanks'),
]

web3auth/urls.py
from django.conf.urls import url

from web3auth import views
app_name = 'web3auth'
urlpatterns = [
    url(r'login_api/$', views.login_api, name='login_api'),
    # url(r'signup_api/$', views.signup_api, name='signup_api'),
    # url(r'signup_view/$', views.signup_view, name='signup_view'),
]

pollSite/models.py
#pollSite


from __future__ import unicode_literals
from django.db import models

# Create your models here.

class siteUrl(models.Model):
	urlText			=	models.CharField(max_length=500)
	rate7			=	models.IntegerField(default=0)
	rate6			=	models.IntegerField(default=0)
	rate5			=	models.IntegerField(default=0)
	rate4			=	models.IntegerField(default=0)
	rate3			=	models.IntegerField(default=0)
	rate2			=	models.IntegerField(default=0)
	rate1			=	models.IntegerField(default=0)
	rateCount		=	models.IntegerField(default=0)
	rating			=	models.FloatField(default=0.0)

class Person(models.Model):
	name			=	models.CharField(max_length=200)
	age				=	models.IntegerField(default=0)
	sex				=	models.IntegerField(default=0)
	education		=	models.IntegerField(default=0)
	count			=	models.IntegerField(default=0)

class Entries(models.Model):
	personId		=	models.ForeignKey(Person, on_delete=models.CASCADE)
	urlId			=	models.ForeignKey(siteUrl, on_delete=models.CASCADE)
	rating			=	models.IntegerField(default=0)

pollSite/views.py
#pollSite
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Entries, Person, siteUrl

import random
import datetime
def index(request):
	args={}
	return render(request,'pollSite/index.html',args)
def register(request):
	args		=	{}
	return render(request,'pollSite/register.html',args)
def detail(request,pk1,pk2):
	siteObj		=	get_object_or_404(siteUrl, pk=pk1)
	PersonObj	=	get_object_or_404(Person, pk=pk2)
	args		=	{'site':siteObj,'person':PersonObj}
	return render(request,'pollSite/detail.html',args)
def results(request,pk):
	siteObj		=	get_object_or_404(siteUrl, pk=pk)
	args		=	{'object':siteObj}
	return render(request,'pollSite/results.html',args)
def thanks(request):
	args		=	{}
	return render(request,'pollSite/thanks.html',args)
def vote(request, siteId, PersonId):
	siteObj		=	get_object_or_404(siteUrl, pk=siteId)
	PersonObj	=	get_object_or_404(Person,  pk=PersonId)
	userRating	= 	request.POST['choice']
	newEntry	=	Entries.objects.create(personId=PersonObj,urlId=siteObj,rating=int(userRating))
	total=0.0
	if userRating=="7":
		siteObj.rate7+=1
		total+=siteObj.rate7
	elif userRating=="6":
		siteObj.rate6+=1
		total+=siteObj.rate6
	elif userRating=="5":
		siteObj.rate5+=1
		total+=siteObj.rate5
	elif userRating=="4":
		siteObj.rate4+=1
		total+=siteObj.rate4
	elif userRating=="3":
		siteObj.rate3+=1
		total+=siteObj.rate3
	elif userRating=="2":
		siteObj.rate2+=1
		total+=siteObj.rate2
	elif userRating=="1":
		siteObj.rate1+=1
		total+=siteObj.rate1
	siteObj.rateCount+=1
	PersonObj.count+=1
	siteObj.rating=1.0*total/siteObj.rateCount
	siteObj.save()
	PersonObj.save()
	if PersonObj.count >=20:
		args={}
		return HttpResponseRedirect(reverse('pollSite:thanks'))
	nextSite	=	list(siteUrl.objects.order_by('rateCount'))[0]
	return HttpResponseRedirect(reverse('pollSite:detail', args=(nextSite.id,PersonObj.id)))
def newPerson(request):
	Name		=	request.POST['Name']
	age			=	request.POST['age']
	sex			=	request.POST['gender']
	education	=	request.POST['education']
	try:
		PersonObj	=	Person.objects.get(name=Name,age=int(age),sex=int(sex),education=int(education))
	except Person.DoesNotExist:
		PersonObj	=	Person.objects.create(name=Name,age=int(age),sex=int(sex),education=int(education))
	if PersonObj.count >=20:
		args={}
		return HttpResponseRedirect(reverse('pollSite:thanks'))
	nextSite	=	list(siteUrl.objects.order_by('rateCount'))[0]
	return HttpResponseRedirect(reverse('pollSite:detail', args=(nextSite.id,PersonObj.id)))

pollSite/templates/pollSite/detail.html
<!-- pollSite -->
{% load static %}
<html>
<head>
<title> Site </title>
<link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
<style media="screen">
.my_iframe {
	margin: 0 auto;
	border: 10px double #808000 ;}
.inputGroup {
  background-color: #bbb;
  display: block;
  margin: 10px 0;
  position: relative;
}
.inputGroup label {
  padding: 12px 30px;
  width: 100%;
  display: block;
  text-align: left;
	color: #000;
  cursor: pointer;
  position: relative;
  z-index: 2;
  transition: color 200ms ease-in;
  overflow: hidden;
}
.inputGroup label:before {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  content: '';
  background-color: #5562eb;
  position: absolute;
  left: 50%;
  top: 50%;
  -webkit-transform: translate(-50%, -50%) scale3d(1, 1, 1);
          transform: translate(-50%, -50%) scale3d(1, 1, 1);
  transition: all 300ms cubic-bezier(0.4, 0, 0.2, 1);
  opacity: 0;
  z-index: -1;
}
.inputGroup label:after {
  width: 32px;
  height: 32px;
  content: '';
  border: 2px solid #D1D7DC;
  background-color: #fff;
  background-image: url("data:image/svg+xml,%3Csvg width='32' height='32' viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M5.414 11L4 12.414l5.414 5.414L20.828 6.414 19.414 5l-10 10z' fill='%23fff' fill-rule='nonzero'/%3E%3C/svg%3E ");
  background-repeat: no-repeat;
  background-position: 2px 3px;
  border-radius: 50%;
  z-index: 2;
  position: absolute;
  right: 30px;
  top: 50%;
  -webkit-transform: translateY(-50%);
          transform: translateY(-50%);
  cursor: pointer;
  transition: all 200ms ease-in;
}
.inputGroup input:checked ~ label {
  color: #000;
}
.inputGroup input:checked ~ label:before {
  -webkit-transform: translate(-50%, -50%) scale3d(56, 56, 1);
          transform: translate(-50%, -50%) scale3d(56, 56, 1);
  opacity: 1;
}
.inputGroup input:checked ~ label:after {
  background-color: #54E0C7;
  border-color: #54E0C7;
}
.inputGroup input {
  width: 32px;
  height: 32px;
  order: 1;
  z-index: 2;
  position: absolute;
  right: 30px;
  top: 50%;
  -webkit-transform: translateY(-50%);
          transform: translateY(-50%);
  cursor: pointer;
  visibility: hidden;
}
.form {
  padding: 0 16px;
  max-width: 550px;
  margin: 50px auto;
  font-size: 18px;
  font-weight: 600;
  line-height: 36px;
}
body {
  background-color: #FFFFFF;//#EEE8AA;
  font-family: 'Fira Sans', sans-serif;
}
*,
*::before,
*::after {
  box-sizing: inherit;
}
html {
  box-sizing: border-box;
}
code {
  background-color: #9AA3AC;
  padding: 0 8px;
}
</style>
</head>
<body>
<div style="width:100%;">
	<div style="float:left; width: 80%">
		<iframe class="my_iframe" width="1400" height="700" src="{{ site.urlText}}" frameborder="0" allowfullscreen></iframe>
	</div>
	<div style="float:left;">
		<form   action="{% url 'pollSite:vote' site.id person.id %}" method="post">
  	<h2>Rate this website.</h2>
		{% csrf_token %}
		{% for rating in "7654321"%}
  		<div class="inputGroup">
    		<input type="radio" name="choice" id="rate{{rating}}" value="{{ rating }}" required="True"/>
    		<label for="rate{{rating}}">{{ rating }}</label>
  		</div>
		{% endfor %}
		<input type="submit" value="vote" />
		</form>
	</div>
</div>
<div style="clear:both"></div>
</body>
</html>

pollSite/templates/pollSite/results.html
{% load static %}
<html>
<head>
<title>Result</title>
<link rel="stylesheet" type="text/css" href="{% static 'pollSite/css/bootstrap.css' %}" />
<head>
<body>
<h1>{{object.question_text}}</h1>
<ul>
{% for choice in object.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'pollSite:detail' object.id %}">Vote again?</a>
</body>
<html>